# This is the main service config file.
# For full config options, check the docs: docs.serverless.com
service: sls-contact-form
# app and org for use with dashboard.serverless.com
app: sls-contact-form
org: aihaddad
# Pin Serverless version
frameworkVersion: ">=1.67.3"

provider:
  name: aws
  stage: dev
  region: ${env:REGION}
  runtime: python3.7
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "ses:SendEmail"
        - "ses:SendRawEmail"
      Resource: "*"
  versionFunctions: false

functions:
  contact:
    handler: handler.contact
    environment:
      SENDER: ${env:SENDER}
      RECEIVER: ${env:RECEIVER}
    events:
      - http:
          path: contact
          method: post
          request:
            schema:
              application/json: ${file(request_schema.json)}
          cors: true

package:
  exclude:
    - .*
    - node_modules/**
    - package-lock.json

plugins:
  - serverless-dotenv-plugin
